version: "3"
services:
  nutmeg-slackbot:
    container_name: nsb
    build: ./slackbot
    env_file:
      - env/prd.env
    volumes:
      - ./slackbot:/work
    ports:
      - 3000:3000
    tty: true
    command: "python main.py"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
      - ./mongo:/data/configdb

  api:
    container_name: "api"
    build:
      context: ./api
    volumes:
      - ./api:/go/src/work
    ports:
      - "1323:1323"
    command: "./start.sh"
    depends_on:
      - mongo

  view:
    build: ./view
    container_name: "view"
    volumes:
      - ./view:/app
    command: "npm run start"
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true
    depends_on:
      - api
    env_file:
      - env/prd.env
    environment:
      NEXT_PUBLIC_SSR_API_URI: "https://relation-slack-api.nutfes.net"
      NEXT_PUBLIC_CSR_API_URI: "https://relation-slack-api.nutfes.net"

  # tunnelName: relation-slack-prd
  cloudflare:
    image: "cloudflare/cloudflared:latest"
    container_name: "cloudflare"
    volumes: ["./cloudflare/production:/home/nonroot/.cloudflared"]
    command: tunnel run
