import '@/styles/globals.css'
import Head from 'next/head'
import { RecoilRoot } from 'recoil'

import { MainLayout } from '@/components/layout/MainLayout'

import type { AppProps } from 'next/app'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>渉外局Slackログ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='icon.png' />
      </Head>
      <RecoilRoot>
        <MainLayout>
          <Component {...pageProps} />
        </MainLayout>
      </RecoilRoot>
    </>
  )
}
